<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.manishdait</groupId>
  <artifactId>mirrornode-clientj</artifactId>
  <version>0.0.1</version>
  <packaging>pom</packaging>

  <name>mirrornode-clientj</name>
  <description>A lightweight, Java client wrapper designed to easily query the Hiero Mirror Node REST API.</description>
  <url>https://github.com/manishdait/mirrornode-clientj</url>

  <licenses>
    <license>
      <name>MIT</name>
      <url>https://github.com/manishdait/mirrornode-clientj/blob/master/LICENSE</url>
    </license>
  </licenses>

  <developers>
    <developer>
      <id>manishdait</id>
      <name>Manish Dait</name>
    </developer>
  </developers>

  <scm>
    <connection>scm:git:git://github.com/manishdait/mirrornode-clientj.git</connection>
    <developerConnection>scm:git:ssh://github.com/manishdait/mirrornode-clientj.git</developerConnection>
    <url>https://github.com/manishdait/mirrornode-clientj</url>
    <tag>HEAD</tag>
  </scm>

  <modules>
    <module>mirrornode-clientj-core</module>
    <module>mirrornode-clientj-example</module>
  </modules>

  <properties>
    <maven.compiler.source>25</maven.compiler.source>
    <maven.compiler.target>25</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <hiero.version>2.72.0</hiero.version>
    <jackson.version>3.1.2</jackson.version>
    <jspecify.version>1.0.0</jspecify.version>
    <junit.version>6.0.3</junit.version>
    <assertj.version>3.27.7</assertj.version>
    <mockito.version>5.23.0</mockito.version>
    <spotless.version>3.4.0</spotless.version>
  </properties>

  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.hedera.hashgraph</groupId>
        <artifactId>sdk</artifactId>
        <version>${hiero.version}</version>
        <scope>compile</scope>
        <exclusions>
          <exclusion>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
          </exclusion>
        </exclusions>
      </dependency>

      <dependency>
        <groupId>tools.jackson.core</groupId>
        <artifactId>jackson-databind</artifactId>
        <version>${jackson.version}</version>
        <scope>compile</scope>
      </dependency>

      <dependency>
        <groupId>org.jspecify</groupId>
        <artifactId>jspecify</artifactId>
        <version>${jspecify.version}</version>
        <scope>compile</scope>
      </dependency>

      <dependency>
        <groupId>org.junit.jupiter</groupId>
        <artifactId>junit-jupiter-api</artifactId>
        <version>${junit.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.assertj</groupId>
        <artifactId>assertj-core</artifactId>
        <version>${assertj.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>org.mockito</groupId>
        <artifactId>mockito-core</artifactId>
        <version>${mockito.version}</version>
        <scope>test</scope>
      </dependency>

      <dependency>
        <groupId>javax.annotation</groupId>
        <artifactId>javax.annotation-api</artifactId>
        <version>1.3.2</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <build>
    <plugins>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>${spotless.version}</version>
        <configuration>
          <java>
            <googleJavaFormat/>
            <formatAnnotations/>
            <trimTrailingWhitespace/>
          </java>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <profiles>
    <profile>
      <id>publication</id>

      <properties>
        <jreleaser.config.file>jreleaser.toml</jreleaser.config.file>
      </properties>

      <build>
        <defaultGoal>deploy</defaultGoal>
        <plugins>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-javadoc-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-javadocs</id>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <attach>true</attach>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-source-plugin</artifactId>
            <executions>
              <execution>
                <id>attach-sources</id>
                <goals>
                  <goal>jar</goal>
                </goals>
                <configuration>
                  <attach>true</attach>
                </configuration>
              </execution>
            </executions>
          </plugin>

          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-deploy-plugin</artifactId>
            <configuration>
              <altDeploymentRepository>local::file:./target/staging-deploy</altDeploymentRepository>
              <altReleaseDeploymentRepository>local::file:./target/staging-deploy</altReleaseDeploymentRepository>
              <altSnapshotDeploymentRepository>local::file:./target/staging-deploy</altSnapshotDeploymentRepository>
            </configuration>
          </plugin>

          <plugin>
            <groupId>org.jreleaser</groupId>
            <artifactId>jreleaser-maven-plugin</artifactId>
            <inherited>false</inherited>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
