package io.github.manishdait.hieromirror.model;

import java.util.HashMap;
import java.util.Map;

public enum TransactionType {
  ATOMIC_BATCH("ATOMICBATCH"),
  CONSENSUS_CREATE_TOPIC("CONSENSUSCREATETOPIC"),
  CONSENSUS_DELETE_TOPIC("CONSENSUSDELETETOPIC"),
  CONSENSUS_SUBMIT_MESSAGE("CONSENSUSSUBMITMESSAGE"),
  CONSENSUS_UPDATE_TOPIC("CONSENSUSUPDATETOPIC"),
  CONTRACT_CALL("CONTRACTCALL"),
  CONTRACT_CREATE_INSTANCE("CONTRACTCREATEINSTANCE"),
  CONTRACT_DELETE_INSTANCE("CONTRACTDELETEINSTANCE"),
  CONTRACT_UPDATE_INSTANCE("CONTRACTUPDATEINSTANCE"),
  CRYPTO_ADD_LIVE_HASH("CRYPTOADDLIVEHASH"),
  CRYPTO_APPROVE_ALLOWANCE("CRYPTOAPPROVEALLOWANCE"),
  CRYPTO_CREATE_ACCOUNT("CRYPTOCREATEACCOUNT"),
  CRYPTO_DELETE("CRYPTODELETE"),
  CRYPTO_DELETE_ALLOWANCE("CRYPTODELETEALLOWANCE"),
  CRYPTO_DELETE_LIVE_HASH("CRYPTODELETELIVEHASH"),
  CRYPTO_TRANSFER("CRYPTOTRANSFER"),
  CRYPTO_UPDATE_ACCOUNT("CRYPTOUPDATEACCOUNT"),
  ETHEREUM_TRANSACTION("ETHEREUMTRANSACTION"),
  FILE_APPEND("FILEAPPEND"),
  FILE_CREATE("FILECREATE"),
  FILE_DELETE("FILEDELETE"),
  FILE_UPDATE("FILEUPDATE"),
  FREEZE("FREEZE"),
  NODE("NODE"),
  NODE_CREATE("NODECREATE"),
  NODE_DELETE("NODEDELETE"),
  NODE_STAKE_UPDATE("NODESTAKEUPDATE"),
  NODE_UPDATE("NODEUPDATE"),
  SCHEDULE_CREATE("SCHEDULECREATE"),
  SCHEDULE_DELETE("SCHEDULEDELETE"),
  SCHEDULE_SIGN("SCHEDULESIGN"),
  SYSTEM_DELETE("SYSTEMDELETE"),
  SYSTEM_UNDELETE("SYSTEMUNDELETE"),
  TOKEN_AIRDROP("TOKENAIRDROP"),
  TOKEN_ASSOCIATE("TOKENASSOCIATE"),
  TOKEN_BURN("TOKENBURN"),
  TOKEN_CANCEL_AIRDROP("TOKENCANCELAIRDROP"),
  TOKEN_CLAIM_AIRDROP("TOKENCLAIMAIRDROP"),
  TOKEN_CREATION("TOKENCREATION"),
  TOKEN_DELETION("TOKENDELETION"),
  TOKEN_DISSOCIATE("TOKENDISSOCIATE"),
  TOKEN_FEE_SCHEDULE_UPDATE("TOKENFEESCHEDULEUPDATE"),
  TOKEN_FREEZE("TOKENFREEZE"),
  TOKEN_GRANT_KYC("TOKENGRANTKYC"),
  TOKEN_MINT("TOKENMINT"),
  TOKEN_PAUSE("TOKENPAUSE"),
  TOKEN_REJECT("TOKENREJECT"),
  TOKEN_REVOKE_KYC("TOKENREVOKEKYC"),
  TOKEN_UNFREEZE("TOKENUNFREEZE"),
  TOKEN_UNPAUSE("TOKENUNPAUSE"),
  TOKEN_UPDATE("TOKENUPDATE"),
  TOKEN_UPDATENFTS("TOKENUPDATENFTS"),
  TOKEN_WIPE("TOKENWIPE"),
  UNCHECKED_SUBMIT("UNCHECKEDSUBMIT"),
  UNKNOWN("UNKNOWN"),
  UTIL_PRNG("UTILPRNG");

  private final String value;
  private static final Map<String, TransactionType> LOOKUP = new HashMap<>();

  static {
    for (TransactionType type : TransactionType.values()) {
      LOOKUP.put(type.value, type);
    }
  }

  TransactionType(String value) {
    this.value = value;
  }

  public String getValue() {
    return this.value;
  }

  public static TransactionType fromValue(String value) {
    return LOOKUP.get(value);
  }
}
