<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.github.manishdait</groupId>
    <artifactId>mirrornode-clientj</artifactId>
    <version>0.0.1</version>
  </parent>

  <artifactId>mirrornode-clientj-example</artifactId>
  <packaging>jar</packaging>

  <name>mirrornode-clientj-examples</name>
  <description>Sample examples for using the mirronode-clientj-core module.</description>
  <url>https://github.com/manishdait/mirrornode-clientj</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.deploy.skip>true</maven.deploy.skip>
    <jreleaser.skip>true</jreleaser.skip>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.manishdait</groupId>
      <artifactId>mirrornode-clientj-core</artifactId>
      <version>0.0.1</version>
    </dependency>
  </dependencies>
</project>
