name: Release Artifacts

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 25
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version: "25"
          distribution: "temurin"
          cache: "maven"

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_KEY_CONTENTS }}" | gpg --batch --import
          mkdir -p ~/.gnupg
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf

      - name: Verify POM Version
        run: |
          POM_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          TAG_VERSION="${GITHUB_REF_NAME#v}"

          if [ "$POM_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch, POM version ($POM_VERSION) does not match tag ($TAG_VERSION)"
            exit 1
          fi

          echo "Success: POM version matches the tag"

      - name: Prepare Hiero Solo
        id: solo
        uses: hiero-ledger/hiero-solo-action@328bc84c3b00a990a151418144fd682a4eb76ea6 # v0.19.0
        with:
          installMirrorNode: true
          soloVersion: v0.69.0
          mirrorNodeVersion: v0.153.0
          hieroVersion: v0.73.0

      - name: Build & Stage
        run: ./mvnw -B -Ppublication deploy

      - name: Publish with JReleaser
        run: ./mvnw -B -Ppublication jreleaser:full-release -N
        env:
          JRELEASER_GPG_SECRET_KEY: ${{ secrets.GPG_KEY_CONTENTS }}
          JRELEASER_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          JRELEASER_MAVENCENTRAL_USERNAME: ${{ secrets.MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD: ${{ secrets.MAVENCENTRAL_PASSWORD }}
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
